# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoMaringa
                                 A QGIS plugin
 Teste para obtenção dos dados do portal Geomaringá
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-08-26
        copyright            : (C) 2025 by Andre Zanco
        email                : andrezanco88@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeoMaringa class from file GeoMaringa.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Geo_Maringa import GeoMaringa
    return GeoMaringa(iface)
